### ISSUE TITLE
[BUG] Low FPS when taking off (V1.0.0 - BETA TEST)

### ISSUE THREAD

**Issue by HaroldHormaechea** [JPLogistics/JPLogistics_C152#109]
With this version, when taking off, my fps will drop to 5, with the main thread taking over 100ms per frame. Additionally, once the game was fully locked (I could alt-tab in and out of it, but nothing would move) and unresponsive, but it didn't trigger the "application is stuck" windows overlay.

I couldn't find a relation between weather and this. When using a different plane during the same game execution (Asobo's default 172) everything went fine at near 30fps as usual in my system.

i7-9750H CPU
GeForce 1550 Gtx Mobile

No other community mods installed

If you need any debug information let me know along with instructions on how to take it.

**Comment by N95JPL** [comment]
Please can you report back with the airfield and runway type?
Grass Strips or heavy weather seem to be causing an issue!

**Comment by HaroldHormaechea** [comment]
It was in dublin EIDW (paved runway), real time weather which was quite bad, but switching it back to clear skies didn't fix the issue. I didn't try launching the flight with clear skies though!

**Comment by N95JPL** [comment]
Without relaunchung the flight, the thread is probably still caught up as the runway wouldn't have dried out etc!

**Comment by HaroldHormaechea** [comment]
I'll try different set-ups later and make you a table, give me a couple hours

**Comment by HaroldHormaechea** [comment]
Instead of a table, it's simpler: With rain, moving over the surface of the world will cause this issue.

I tested it several times, and the easiest way to reproduce is:
- Take off with clear skies
- Switch to rain
- Touch down
- Have fun @5fps

**Comment by N95JPL** [comment]
Perfect, thanks for this!
That also narrows down to what's causing it!
I'm looking for a fix!

**Comment by HaroldHormaechea** [comment]
The issue is fixed in the 1.0.0 BETA 2 version, thanks a lot!
