### ISSUE TITLE
[BUG] Engine will easily quit, and will not be restartable. Ramp starts are impossible to do

### ISSUE THREAD

**Issue by HaroldHormaechea** [JPLogistics/JPLogistics_C152#113]
As described, I'm unable to do ramp starts, as the engine will fail to keep RPM even with full throttle. I also tried to start with the engine on, turn it of and restart it, and the same issue will happen.

I created a YT video to showcase the issue: 

- Starting from the runway with engine on: https://youtu.be/rYutHgbG7Bw

- Ramp start: https://youtu.be/rxYNDzg9blA

The first video's description has a timeline of the issues, as it's pretty long at over seven minutes. The second one is shorter and more to the point.

**Summary:**
- Start in the runway
- Fuel mixture cut
- Engine will quit
- Fuel mixture full rich
- Attempt to restart the engine
-- The engine will start and keep RPM (sometimes)
-- Fuel mixtue cut again, engine will quit.
-- Fuell mixture full rich
-- Attempt to restart the engine
- The RPM will slowly go down until the engine quits
- At this point, attempting to restart the engine yields no results.

Additionally, keeping the throttle at minimum will make the engine quit, which didn't happen before.

**Comment by N95JPL** [comment]
I'm pretty sure I know what's causing this issue and WeptBurrito submitted a fix to me earlier today for it!
We had some values upside down with the new Engine Start configuration!
Beta 3 will hopefully solve this when I get chance to release it!

Thanks for such an awesome bug report!

**Comment by N95JPL** [comment]
Hopefully this should be sorted now!
