### ISSUE TITLE
Sending  COM1_VOLUME_INC command does not turn on Radio

### ISSUE THREAD

**Issue by jeffdamp-wave** [JPLogistics/JPLogistics_C152#117]
1. Using the underlying MSFS2020 WASM module to increment the COM1 or COM2 volume from the off position by sending EVENT: Cntrl= 66979 (0x000105a3), Param= 0 (0x00000000) COM1_VOLUME_INC or EVENT: Cntrl= 66982 (0x000105a6), Param= 0 (0x00000000) COM2_VOLUME_INC
Result: 
Radio does NOT turn on but volume knob moves from the off position.

1. Use the mouse to move the volume one click to the right.
Result:
Radio now turns on and can then be turned on and off by sending the COM<x>_VOLUME_INC/COM<x>_VOLUME_DEC events.

Expected:
The radio should turn on when receiving the COM<x>_VOLUME_INC from the off position.

**Comment by N95JPL** [comment]
This is a known thing I've been fighting with for a while!
Rest assured I'm working on it but not yet successful!

**Comment by N95JPL** [comment]
This is linked to Issue #50
Ill close this one and keep #50 open!
