### ISSUE TITLE
VOR TO/FROM flags hidden

### ISSUE THREAD

**Issue by mhostetter** [JPLogistics/JPLogistics_C152#158]
The VOR TO/FROM flag is hidden by default. When right-clicking and panning the camera, they become visible again. I'm using MSFS 2020 Update 7. If you can point me in the right direction, I'd be happy to submit a PR.

Here's a picture by default. Once right clicking the flags appear again.

![image](https://user-images.githubusercontent.com/12112573/142967652-ea1d41b6-fa2b-469e-8009-79928a9b9ed1.png)

**Comment by weptburrito** [comment]
Hey there, unfortunately I am unable to reproduce either the flag or the sound issue.

I am more focused on the large negative numbers on your DME. They are normally from 0 to 99.99 and showing -2218:33 tells me something may not have loaded up right.  I've seen this reported a couple of times but has never been reproduced, even by the OP. Theory is it may have something to do in the sim regarding VORTAC or TACAN
![Screenshot (647)](https://user-images.githubusercontent.com/82721974/142985516-a47e68c4-9c45-47d2-ad08-6c42a52d6417.png)

**Comment by mhostetter** [comment]
Thanks for the reply. This morning I tried three airports and VORs to try to reproduce and haven't so far. Strange... I encountered the original issue while flying for some time (using fast forward mode occasionally -- don't know if that's involved).

The only reproducible scenario I found was this. While I was able to get the TO/FROM flags and correct Morse code, I encountered the negative travel time you mentioned.

Airport: G05 Finleyville, PA, USA
VOR: Allegheny AGC 110.0 MHz

![image](https://user-images.githubusercontent.com/12112573/143048069-b4383e80-d43a-49b7-8ed9-ea4f14d9ece8.png)

Game load 1

![image](https://user-images.githubusercontent.com/12112573/143032411-a85dd478-9a3a-4a3f-99db-5a13c95b39ec.png)

Game load 2

![image](https://user-images.githubusercontent.com/12112573/143037136-662a189b-7c79-48af-b842-3ff68d3b04bf.png)

Interestingly, by happenstance I let the game / engine idle for a while and when I looked again the travel time returned to "99:59". Maybe there's a bug there, not sure.

But as of yet, I can't reproduce the issue as filed. I'll see if I encounter it again. If not, I'll close it.

**Comment by mhostetter** [comment]
I determined what my issue was with the TO/FROM flags. I didn't realize my Honeycomb Bravo throttle quadrant had my parking brake button also mapped to Avionics 1. So when I was on the ground (with parking brake on) it worked, and in the air with parking brake off Avionics 1 was off and the flags were hidden.

![image](https://user-images.githubusercontent.com/12112573/143083035-c137f2d9-bc54-45e9-89cd-c2576adb4db5.png)

Sorry for the false report. This wasn't as obvious as the cause of the NAV1 audio from #157, but is likely related. I'll close that if I can't reproduce it.
