### ISSUE TITLE
Is this plane affected by the new aerodynamics in Sim Update 8?

### ISSUE THREAD

**Issue by DarthJahus** [JPLogistics/JPLogistics_C152#173]

**Comment by Aesculab** [comment]
It isn't but as stated by somebody in Discord, you could integrate it by yourself if you want them now.

_

> "For you or anyone else interested, and if you like how the stock 152 flies, there would be no problem copying the engine.cfg and flight_model.cfg from the stock plane and putting that into this mod.  This Path to those files are  ..\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Official\OneStore\asobo-aircraft-c152\SimObjects\Airplanes\Asobo_C152"

_

**Comment by DarthJahus** [comment]
Thank you, @Aesculab. Much appreciated.
