### ISSUE TITLE
Whiskey Compass Jerky

### ISSUE THREAD

**Issue by johnwillimas** [JPLogistics/JPLogistics_C152#174]
I've only just noticed this. I'm running the Sim Update 9 beta and flying on a heading of 355 degrees. When passing through 000 degrees (North) the heading indicator suddenly jerks and then resumes its normal slow reaction. Turning back through a headingof 000 degrees has the same effect. Problem is present on both fairing and non-fairing versions.

**Comment by weptburrito** [comment]
Thanks for the post. This is a known animation bug...but should be fixed in a future update.

**Comment by johnwillimas** [comment]
Good oh!
