### ISSUE TITLE
Transponder inputs don't seem accessible via MobiFlight

### ISSUE THREAD

**Issue by thestonefox** [JPLogistics/JPLogistics_C152#180]
I have a custom transponder set up with Mobiflight inputs (based on the original C152 transponder as found in the default asobo 152)

My mobiflight inputs are like:

`Transponder Off` -> `0 (>A:TRANSPONDER STATE:1, Enum)`
`Transponder Stand By` -> `1 (>A:TRANSPONDER STATE:1, Enum)`
etc...

and I also have a button set up for `XPNDR_IDENT_TOGGLE`

These all work fine in the Asobo 152 but do nothing in this modded 152.

**Comment by N95JPL** [comment]
This repo is no longer maintained by JPLogistics
The project was handed over to WeptBurrito some time ago due to time commitment constraints

I'd recommend you direct the issue to the C152 Discord Server which is still active and many others use Mobiflight

https://discord.gg/GPzfkJGK

Cheers
JPL

**Comment by thestonefox** [comment]
Thanks for the info
