### ISSUE TITLE
[FEATURE] Baggage!

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/JPLogistics_C152#65]
**Is your feature request related to a problem? Please describe.**
The cargo-hold looks kind of empty...

**Describe the solution you'd like**
Lets see some items in there, based on the weight inputted!

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by N95JPL** [comment]
Excellent idea, I am going to include lighter weight stuff, this will be reflected by the weight inputted in the Payload area!

**Comment by EricFlight** [comment]
The tow bar should probably be in the back permanently when thinking about being totally authentic.

**Comment by N95JPL** [comment]
I've got it on my list to sort!
Thanks for the idea!

**Comment by EricFlight** [comment]
First aid kit too...for emergencies
