### ISSUE TITLE
Request add transponder Ident and power knob access

### ISSUE THREAD

**Issue by jeffdamp-wave** [JPLogistics/JPLogistics_C152#99]
Can you either swap the existing C152 Transponder with the KT76C or add H: or K: variables to these controls?  I use a custom cockpit powered by Mobiflight and FSUIPC.   The KT76C has event handlers already that work with Mobiflight.
https://youtu.be/PKBjEl9E5A4?t=286 

Thanks, Jeff

**Comment by N95JPL** [comment]
I've wanted to change the Transponder but I haven't had the time to make it possible in V1.0.0 but I am making custom logic for it... so I will look at using H: vars, thanks for the link, if not seen H before!

**Comment by N95JPL** [comment]
Hello!
Situation update, we've upgraded the Transponder System!
We are now rocking a AS330 - Unfortunately I don't have access to the KT76C Model files, so we have gone for this one!

Hopefully that helps!
